[package]
name = "m-bus-parser"
version = "0.0.9"
edition = "2021"
description = "A library for parsing M-Bus frames"
license = "MIT"
homepage = "https://maebli.github.io/"
repository = "https://github.com/maebli/m-bus-parser"
readme = "README.md"
authors = ["Michael Aebli"]
keywords = ["m-bus", "parser", "parse"]
exclude = ["/resources", "/tests", "/benches", "examples"]

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dev-dependencies]
criterion = "0.5.1"
walkdir = "2.5.0"
hex = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = "0.6.0"

[build-dependencies]
bindgen = "0.69.4"

[features]
std = []
plaintext-before-extension = []
serde = ["dep:serde", "std", "arrayvec/serde", "bitflags/serde"]

[profile.release]
opt-level = 'z'   # Optimize for size
lto = true        # Enable Link Time Optimization
codegen-units = 1 # Reduce codegen units to improve optimizations

[profile.release.package."m-bus-parser-wasm-pack"]
opt-level = "s"

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
bitflags = "2.4.2"
arrayvec = { version = "0.7.4", optional = false, default-features = true }

[workspace]
members = ["cli", "wasm"]
